"""Cria tabelas iniciais para amigos, itens e emprestimos

Revision ID: 5fe45e35192c
Revises: 
Create Date: 2025-08-10 17:13:36.929096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe45e35192c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amigos_id'), 'amigos', ['id'], unique=False)
    op.create_index(op.f('ix_amigos_nome'), 'amigos', ['nome'], unique=True)
    op.create_index(op.f('ix_amigos_telefone'), 'amigos', ['telefone'], unique=True)
    op.create_table('itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_id'), 'itens', ['id'], unique=False)
    op.create_index(op.f('ix_itens_nome'), 'itens', ['nome'], unique=False)
    op.create_table('emprestimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_emprestimo', sa.Date(), nullable=False),
    sa.Column('data_devolucao', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'DEVOLVIDO', name='statusemprestimo'), nullable=False),
    sa.Column('amigo_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amigo_id'], ['amigos.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emprestimos_id'), 'emprestimos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emprestimos_id'), table_name='emprestimos')
    op.drop_table('emprestimos')
    op.drop_index(op.f('ix_itens_nome'), table_name='itens')
    op.drop_index(op.f('ix_itens_id'), table_name='itens')
    op.drop_table('itens')
    op.drop_index(op.f('ix_amigos_telefone'), table_name='amigos')
    op.drop_index(op.f('ix_amigos_nome'), table_name='amigos')
    op.drop_index(op.f('ix_amigos_id'), table_name='amigos')
    op.drop_table('amigos')
    # ### end Alembic commands ###
